// Code generated by "stringer -type=TokenKind -linecomment"; DO NOT EDIT.

package lexer

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TokenKindEOF-0]
	_ = x[TokenKindBOF-1]
	_ = x[TokenKindError-2]
	_ = x[TokenKindComment-3]
	_ = x[TokenKindUnderscore-4]
	_ = x[TokenKindEqual-5]
	_ = x[TokenKindComma-6]
	_ = x[TokenKindColon-7]
	_ = x[TokenKindSemicolon-8]
	_ = x[TokenKindDot-9]
	_ = x[TokenKindLeftBrace-10]
	_ = x[TokenKindLeftSquare-11]
	_ = x[TokenKindLeftParen-12]
	_ = x[TokenKindLeftAngle-13]
	_ = x[TokenKindRightBrace-14]
	_ = x[TokenKindRightSquare-15]
	_ = x[TokenKindRightParen-16]
	_ = x[TokenKindRightAngle-17]
	_ = x[TokenKindSlash-18]
	_ = x[TokenKindInt-19]
	_ = x[TokenKindFloat-20]
	_ = x[TokenKindStr-21]
	_ = x[TokenKindIdentifier-128]
	_ = x[TokenKindSyntax-129]
	_ = x[TokenKindEdition-130]
	_ = x[TokenKindPackage-131]
	_ = x[TokenKindImport-132]
	_ = x[TokenKindPublic-133]
	_ = x[TokenKindWeak-134]
	_ = x[TokenKindOption-135]
	_ = x[TokenKindReserved-136]
	_ = x[TokenKindTo-137]
	_ = x[TokenKindMax-138]
	_ = x[TokenKindEnum-139]
	_ = x[TokenKindMessage-140]
	_ = x[TokenKindMap-141]
	_ = x[TokenKindRepeated-142]
	_ = x[TokenKindOptional-143]
	_ = x[TokenKindOneOf-144]
	_ = x[TokenKindExtensions-145]
	_ = x[TokenKindService-146]
	_ = x[TokenKindRPC-147]
	_ = x[TokenKindReturns-148]
	_ = x[TokenKindExtend-149]
	_ = x[TokenKindTrue-150]
	_ = x[TokenKindFalse-151]
	_ = x[TokenKindTypeFloat-152]
	_ = x[TokenKindTypeDouble-153]
	_ = x[TokenKindTypeInt32-154]
	_ = x[TokenKindTypeInt64-155]
	_ = x[TokenKindTypeUint32-156]
	_ = x[TokenKindTypeUint64-157]
	_ = x[TokenKindTypeSint32-158]
	_ = x[TokenKindTypeSint64-159]
	_ = x[TokenKindTypeFixed32-160]
	_ = x[TokenKindTypeFixed64-161]
	_ = x[TokenKindTypeSfixed32-162]
	_ = x[TokenKindTypeSfixed64-163]
	_ = x[TokenKindTypeBool-164]
	_ = x[TokenKindTypeString-165]
	_ = x[TokenKindTypeBytes-166]
}

const (
	_TokenKind_name_0 = "EOFBOFErrorComment_=,:;.{[(<}])>/IntegerFloatString"
	_TokenKind_name_1 = "Identifiersyntaxeditionpackageimportpublicweakoptionreservedtomaxenummessagemaprepeatedoptionaloneofextensionsservicerpcreturnsextendtruefalsefloatdoubleint32int64uint32uint64sint32sint64fixed32fixed64sfixed32sfixed64boolstringbytes"
)

var (
	_TokenKind_index_0 = [...]uint8{0, 3, 6, 11, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 40, 45, 51}
	_TokenKind_index_1 = [...]uint8{0, 10, 16, 23, 30, 36, 42, 46, 52, 60, 62, 65, 69, 76, 79, 87, 95, 100, 110, 117, 120, 127, 133, 137, 142, 147, 153, 158, 163, 169, 175, 181, 187, 194, 201, 209, 217, 221, 227, 232}
)

func (i TokenKind) String() string {
	switch {
	case i <= 21:
		return _TokenKind_name_0[_TokenKind_index_0[i]:_TokenKind_index_0[i+1]]
	case 128 <= i && i <= 166:
		i -= 128
		return _TokenKind_name_1[_TokenKind_index_1[i]:_TokenKind_index_1[i+1]]
	default:
		return "TokenKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
