package typecheck

import (
	"strings"

	"github.com/Clement-Jean/protein/lexer"
	"github.com/Clement-Jean/protein/parser"
	"github.com/Clement-Jean/protein/symtab"
	"github.com/Clement-Jean/protein/unit"
)

func collectOptionName(idx uint32, unit *unit.Unit, start lexer.TokenInfo) (uint32, string) {
	var name strings.Builder

	for start.Kind.IsIdentifier() || start.Kind == lexer.TokenKindDot || start.Kind == lexer.TokenKindLeftParen || start.Kind == lexer.TokenKindRightParen {
		end := unit.Toks.TokenInfos[idx+1]
		part := string(unit.Buffer.Range(start.Offset, end.Offset))

		// FIX: this is a hack for avoiding reading the field name
		if strings.HasSuffix(part, " ") {
			name.WriteString(strings.TrimSpace(part))
			break
		}

		name.WriteString(part)
		idx++
		start = unit.Toks.TokenInfos[idx]
	}

	return idx + 1, name.String()
}

// FIX: this should be generated by reading the descriptor.proto
//   - locate the file
//   - parse
//   - read all the fields of google.protobuf.FileOptions
//   - register them as knownFileOptions
var knownFileOptions = map[string]struct{}{
	"deprecated":           {},
	"java_package":         {},
	"java_outer_classname": {},
	"java_multiple_files":  {},
	"optimize_for":         {},
	"go_package":           {},
	"csharp_namespace":     {},
	"objc_class_prefix":    {},
	"cc_enable_arenas":     {},
}

func (tc *TypeChecker) handleFileOption(sym *symtab.Symtab, scope []string, unit *unit.Unit, idx uint32) error {
	start := unit.Toks.TokenInfos[idx]
	_, id := collectOptionName(idx, unit, start)

	if _, ok := knownFileOptions[id]; ok {
		return nil
	}

	line, col := tc.getLineColumn(unit, start.Offset)

	// TODO not sure if the scope is needed here
	//      maybe we should search/add to strings.Join(scope, ".") ?
	decl, ok := sym.SearchDecl(".")
	if !ok {
		decl = symtab.Decl{
			Unit:   unit,
			Name:   ".",
			Type:   parser.NodeKindOptionFile,
			Fields: make(map[string]symtab.Ref),
		}
		sym.Decls["."] = decl
	}

	lParen := strings.IndexByte(id, '(')
	rParen := strings.IndexByte(id, ')')
	typeName := id

	if lParen != rParen {
		typeName = id[lParen+1 : rParen]
	}

	if !strings.HasPrefix(typeName, ".") {
		typeName = "." + typeName
	}

	ref := symtab.Ref{
		Unit:     unit,
		Line:     line,
		Col:      col,
		TypeName: typeName,
	}
	sym.AddRef(&decl, id, 0, ref)
	return nil
}
