// Code generated by "stringer -type=state"; DO NOT EDIT.

package parser

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[stateTopLevel-0]
	_ = x[stateSyntaxAssign-1]
	_ = x[stateSyntaxFinish-2]
	_ = x[stateEditionAssign-3]
	_ = x[stateEditionFinish-4]
	_ = x[stateImportValue-5]
	_ = x[stateImportFinish-6]
	_ = x[statePackageFinish-7]
	_ = x[stateOptionName-8]
	_ = x[stateOptionNameRest-9]
	_ = x[stateOptionNameParenFinish-10]
	_ = x[stateOptionAssign-11]
	_ = x[stateOptionFinish-12]
	_ = x[stateTextFieldValue-13]
	_ = x[stateTextFieldAssign-14]
	_ = x[stateTextFieldName-15]
	_ = x[stateTextMessageValue-16]
	_ = x[stateTextMessageComma-17]
	_ = x[stateTextMessageFinish-18]
	_ = x[stateFullIdentifierRoot-19]
	_ = x[stateFullIdentifierRest-20]
}

const _state_name = "stateTopLevelstateSyntaxAssignstateSyntaxFinishstateEditionAssignstateEditionFinishstateImportValuestateImportFinishstatePackageFinishstateOptionNamestateOptionNameReststateOptionNameParenFinishstateOptionAssignstateOptionFinishstateTextFieldValuestateTextFieldAssignstateTextFieldNamestateTextMessageValuestateTextMessageCommastateTextMessageFinishstateFullIdentifierRootstateFullIdentifierRest"

var _state_index = [...]uint16{0, 13, 30, 47, 65, 83, 99, 116, 134, 149, 168, 194, 211, 228, 247, 267, 285, 306, 327, 349, 372, 395}

func (i state) String() string {
	if i >= state(len(_state_index)-1) {
		return "state(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _state_name[_state_index[i]:_state_index[i+1]]
}
