// Code generated by "stringer -type=state"; DO NOT EDIT.

package parser

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[stateTopLevel-0]
	_ = x[stateSyntaxAssign-1]
	_ = x[stateSyntaxFinish-2]
	_ = x[stateEditionAssign-3]
	_ = x[stateEditionFinish-4]
	_ = x[stateImportValue-5]
	_ = x[stateImportFinish-6]
	_ = x[statePackageFinish-7]
	_ = x[stateOptionName-8]
	_ = x[stateOptionNameRest-9]
	_ = x[stateOptionNameParenFinish-10]
	_ = x[stateOptionAssign-11]
	_ = x[stateOptionEqual-12]
	_ = x[stateOptionFinish-13]
	_ = x[stateTextFieldValue-14]
	_ = x[stateTextFieldAssign-15]
	_ = x[stateTextFieldName-16]
	_ = x[stateTextFieldExtensionName-17]
	_ = x[stateTextFieldExtensionNameFinish-18]
	_ = x[stateTextMessageValue-19]
	_ = x[stateTextMessageInsert-20]
	_ = x[stateTextMessageFinishRightBrace-21]
	_ = x[stateTextMessageFinishRightAngle-22]
	_ = x[stateMessageBlock-23]
	_ = x[stateMessageFieldAssign-24]
	_ = x[stateMessageFieldOption-25]
	_ = x[stateMessageFieldOptionFinish-26]
	_ = x[stateMessageFieldFinish-27]
	_ = x[stateMessageMapKeyValue-28]
	_ = x[stateMessageValue-29]
	_ = x[stateMessageFinish-30]
	_ = x[stateReservedRange-31]
	_ = x[stateReservedName-32]
	_ = x[stateReservedFinish-33]
	_ = x[stateEnumBlock-34]
	_ = x[stateEnumValue-35]
	_ = x[stateEnumFinish-36]
	_ = x[stateOneofBlock-37]
	_ = x[stateOneofValue-38]
	_ = x[stateOneofFinish-39]
	_ = x[stateServiceBlock-40]
	_ = x[stateServiceValue-41]
	_ = x[stateServiceFinish-42]
	_ = x[stateIdentifier-43]
	_ = x[stateFullIdentifierRoot-44]
	_ = x[stateFullIdentifierRest-45]
	_ = x[stateEnder-46]
}

const _state_name = "stateTopLevelstateSyntaxAssignstateSyntaxFinishstateEditionAssignstateEditionFinishstateImportValuestateImportFinishstatePackageFinishstateOptionNamestateOptionNameReststateOptionNameParenFinishstateOptionAssignstateOptionEqualstateOptionFinishstateTextFieldValuestateTextFieldAssignstateTextFieldNamestateTextFieldExtensionNamestateTextFieldExtensionNameFinishstateTextMessageValuestateTextMessageInsertstateTextMessageFinishRightBracestateTextMessageFinishRightAnglestateMessageBlockstateMessageFieldAssignstateMessageFieldOptionstateMessageFieldOptionFinishstateMessageFieldFinishstateMessageMapKeyValuestateMessageValuestateMessageFinishstateReservedRangestateReservedNamestateReservedFinishstateEnumBlockstateEnumValuestateEnumFinishstateOneofBlockstateOneofValuestateOneofFinishstateServiceBlockstateServiceValuestateServiceFinishstateIdentifierstateFullIdentifierRootstateFullIdentifierReststateEnder"

var _state_index = [...]uint16{0, 13, 30, 47, 65, 83, 99, 116, 134, 149, 168, 194, 211, 227, 244, 263, 283, 301, 328, 361, 382, 404, 436, 468, 485, 508, 531, 560, 583, 606, 623, 641, 659, 676, 695, 709, 723, 738, 753, 768, 784, 801, 818, 836, 851, 874, 897, 907}

func (i state) String() string {
	if i >= state(len(_state_index)-1) {
		return "state(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _state_name[_state_index[i]:_state_index[i+1]]
}
